Exit early when trigger process fails
fermyon/spin pull request #1675
Opened 2023-07-20 13:16 UTC by rylev

Fixes #966 

This exits the main process if the trigger subprocess fails early.

2023-07-20 14:23 UTC, lann requested changes
I'm pretty sure this will leave tempfiles behind.

2023-07-20 14:31 UTC, lann commented
As an alternative, we could introduce a `ExitStatusError` (mirroring the unstable `std::process::ExitStatusError`), downcast to it in our outer `main`, and `exit(err.code)` there.

2023-07-20 16:08 UTC, rylev commented
Good point. I'll move to your suggestion.

2023-07-25 17:02 UTC, lann approved these changes
Thanks! Non-blocking suggestion to add a comment at the downcast site.

2023-07-25 17:29 UTC, lann approved these changes

2023-07-25 18:33 UTC, merged