Create working dir if it does not exist
fermyon/spin pull request #1691
Opened 2023-08-14 12:21 UTC by rylev

Currently we error if the working directory does not exist already.

2023-08-14 20:03 UTC, itowlson requested changes
I can't remember what discussions we had at the time about whether implicit directory creation was good (so convenient) or bad (what if they meant `~/myapps` but typoed `~/maypps`) - other people may have views on this...

2023-08-23 22:41 UTC, vdice commented
E2e tests should now run successfully, just need to rebase.  Though, it looks like there is a failure in the Go SDK tests as well.

2023-08-25 16:00 UTC, rylev commented on src/commands/up.rs
> +        Ok(working_dir)
Very good catch! I'll change that and make a comment.

2023-08-25 16:04 UTC, rylev commented
@itowlson the issue around the temp directory has been fixed. How do you want to make a call on whether auto creation of the working dir is the right way to go?

2023-08-27 19:58 UTC, itowlson approved these changes
LGTM - thanks for adding the comment.

Re whether the behaviour is desirable or not, I can't find any record of the alleged previous discussion.  I don't have strong feelings either way, so I guess either wield your maintainer powers or do a quick poll in Discord?

2023-09-12 09:31 UTC, mikkelhegn commented
LGTM

2023-09-12 09:32 UTC, merged

2023-09-12 09:33 UTC, rylev commented
Note to future selves - this was discussed by several folks including @mikkelhegn and @melissaklein24, and everyone seemed relatively happy with this small change.