Move mysql interface to resources
fermyon/spin pull request #1900
Opened 2023-10-16 19:16 UTC by rylev

The same thing as #1886 but for mysql - this changes the mysql interface to use a connection oriented resource.

2023-10-17 17:11 UTC, lann approved these changes

2023-10-17 17:11 UTC, lann commented on crates/outbound-mysql/src/lib.rs
> +                .map_err(|_| v2::Error::Other("too many connections".into()))
Should this be a `ConnectionFailed` too?

2023-10-17 17:12 UTC, fibonacci1729 commented on wit/preview2/mysql.wit
> +  /// Errors related to interacting with Mysql.
question / super nit: is it Mysql or MySQL?

2023-10-17 17:13 UTC, fibonacci1729 approved these changes

2023-10-17 21:12 UTC, michelleN requested changes

2023-10-17 21:12 UTC, michelleN commented on wit/preview2/mysql.wit
> +    /// Open a connection to the Postgres instance at `address`.
`Postgres` -> `MySQL`?

2023-10-18 09:13 UTC, rylev commented
Merging as all the feedback has been addressed.

2023-10-18 09:13 UTC, merged