feat(sdk/go): implement mysql SDK for TinyGo
fermyon/spin pull request #1922
Opened 2023-10-22 07:51 UTC by Patrick0308

feat(sdk/go): implement mysql SDK for TinyGo

2023-10-22 07:56 UTC, Patrick0308 commented
The code about rdbms is similar on different db sdk. @adamreese  Should we move rdbms code into a internal pkg?

2023-10-24 16:46 UTC, adamreese commented
I'm not sure if there's much code we can share because the C types that are generated per API are distinct types.

2023-10-24 16:50 UTC, adamreese requested changes

2023-10-24 16:50 UTC, adamreese commented on sdk/go/Makefile
> +# build-examples: $(EXAMPLES_DIR)/tinygo-pgsql/main.wasm
Why is this commented out?

2023-10-24 16:50 UTC, adamreese commented on examples/tinygo-outbound-pg/spin.toml
> +environment = { DB_URL = "mysql://spin:spin@127.0.0.1/spin_dev" }
This should reference a postgres db

2023-10-24 16:50 UTC, adamreese commented on examples/tinygo-outbound-pg/main.go
> +		// address of the Mysql server.
```suggestion
		// address of the Postgres server.
```

2023-10-25 11:52 UTC, Patrick0308 commented
I tested executing outbound pg sql with parameters that was failed. Error log is 
```
query failed: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42601), message: "syntax error at or near \",\"", detail: None, hint: None, position: Some(Original(27)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("scan.l"), line: Some(1180), routine: Some("scanner_yyerror") }) }
```
It's same on rust outbound pg sdk too.

2023-10-25 23:39 UTC, adamreese approved these changes
Huge thanks for more great work!

2023-10-25 23:40 UTC, merged