Fix incorrect instructions in outbound hosts error message
fermyon/spin pull request #2045
Opened 2023-11-03 20:00 UTC by adamreese

Fixes #2044

2023-11-05 21:04 UTC, itowlson requested changes
![AB2FB643-F1D7-456F-95A9-DE318FFF01D3-768x432-450245981](https://github.com/fermyon/spin/assets/865538/26938f8e-9caf-42a0-95fb-0bebebdef6ee)

2023-11-05 21:04 UTC, itowlson commented on crates/outbound-http/src/host_impl.rs
> +            u.port().unwrap()
The URL not including a port seems like a highly likely situation.  We should not panic if it happens - just return a host with no port.  (Heck, even if it's unlikely it doesn't merit a panic...)

2023-11-05 21:04 UTC, itowlson commented on crates/outbound-http/src/host_impl.rs
> +            u.host().unwrap(),
This does not merit a panic.  It should return `None` as the original function did.

2023-11-06 19:51 UTC, itowlson commented
@adamreese At the risk of having my own Rust skills forensically disassembled, given that the function returns an Option, I would suggest using the `?` operator e.g. `u.host()?`.  If `host` returns None, this will have the function return None immediately.

For the port thing, though, I think you will need to pattern match, because you don't want to nope out just because the URL doesn't contain  a port. E.g. something like `let port_str = match u.port() { Some(p) => format!(":{p}"), None => "".to_owned() };` (only nicer).  Although as @rylev notes the syntax for `allowed_outbound_hosts` is different anyway.

2023-12-07 01:46 UTC, fibonacci1729 commented
Closing since it appears #2136 addresses this.

2023-12-07 01:46 UTC, closed without merging