Mutable access to request headers
fermyon/spin pull request #2187
Opened 2023-12-17 21:44 UTC by itowlson

Fixes #2186.

This ended up being not symmetric with `Request::headers()` but I couldn't see a way to get closer (e.g. `iter_mut()` didn't seem like it would allow for inserts).  It also surfaces the implementation in what feels like a rather raw way.  @rylev Please feel free to close in favour of a better way if you have one, I'd love a learning opportunity!

2023-12-18 12:04 UTC, rylev requested changes
The function was added to the `Response` type which I don't think was intended? In any case, would it be possible to use `set_header` instead of having mutable access to the headers collection?

2023-12-18 14:59 UTC, lann commented
> The function was added to the `Response` type which I don't think was intended? In any case, would it be possible to use `set_header` instead of having mutable access to the headers collection?

:+1: for `set_header` to match the behavior of https://docs.rs/spin-sdk/2.1.0/spin_sdk/http/struct.RequestBuilder.html#method.header

2023-12-18 18:46 UTC, itowlson commented
Well, doh.  Thanks for the catch and guidance.  Updated.

2023-12-19 09:47 UTC, rylev approved these changes

2023-12-19 18:57 UTC, merged