Allow sqlite migrations for non-default databases.
fermyon/spin pull request #2610
Opened 2024-07-01 15:31 UTC by rylev

Fixes #2607

The database will be selected by the name of the migration file. This makes the name of the migration file significant, whereas previously it was not. If the name of the file and a known database don't line up, `spin up` will fail with an error message.

2024-07-01 21:00 UTC, itowlson requested changes
Given we have docs that use examples like `spin up --sqlite @migrations.sql`, and that migrations may come as a sequence of files (a la `migrations001.sql`, `migrations002.sql`, etc.), I'm reluctant to adopt this UI.  Let's instead look for a more structured and specific syntax, such as `--sqlite custom-db:@migrations.sql` or `--sqlite @migrations.sql>custom-db` (the latter would presumably make shells mad but just trying to spark ideas).

2024-07-02 18:59 UTC, itowlson commented
`@file.sql:database-name` works for me.  Thanks!

2024-07-03 13:07 UTC, rylev commented
@itowlson ok done!

2024-07-03 21:52 UTC, itowlson approved these changes
Couple of non-blocking suggestions, but before merging could you double check that the indents around lines 76-78 are right in the real code?  I'm assuming a GH artifact but good to be sure!  Otherwise LGTM - thanks!

2024-07-03 21:52 UTC, itowlson commented on crates/trigger/src/runtime_config/sqlite.rs
> +        );
It may be GH preview silliness but lines 76-78 seem confusingly outdented?

2024-07-03 21:52 UTC, itowlson commented on crates/trigger/src/runtime_config/sqlite.rs
> +        if let Some(config) = m.strip_prefix('@') {
For me the argument parser is now complicated enough to merit pulling out into a function (ideally with a few simple tests).  I know some folks have different tolerances for this though, especially as you'd probably need to add an enum for the "file vs literal SQL" distinction.  Definitely not a blocker!

2024-07-03 21:52 UTC, itowlson commented on crates/trigger/src/runtime_config/sqlite.rs
> +                Some((file, database)) if database.trim().is_empty() => (file.trim(), "default"),
This would be the `@file.sql:` case?  That feels a bit like a syntax error to me but I don't feel strongly - not a blocker.

2024-07-22 13:12 UTC, merged