Azure Cosmos multiple stores per container
fermyon/spin pull request #2953
Opened 2024-12-13 11:44 UTC by rylev

Fixes #2951 

This adds support in the Azure Cosmos key-value implementation for storing multiple key-value stores in a single Azure Cosmos container. 

**IMPORTANT**: This currently does not change the Spin CLI experience at all. Users of Spin CLI continue to have the 1 to 1 relationship between containers and key-value stores. This only allows Spin runtime embedders the ability to have many stores per containers. We can consider changing the default behavior for the Spin CLI in the future, but this might need to be at a major version change. 

For embedders who provide an `app_id` to the `KeyValueAzureCosmos`, stores will be created in the supplied container and each key/value pair will include a partition_key field in the form of "$app_id/$store_id".

cc @devigned

2024-12-18 15:41 UTC, calebschoepp approved these changes
I have very little familiarity with this code, but reading through it it seems plausibly correct!

2024-12-18 15:41 UTC, calebschoepp commented on crates/key-value-azure/src/store.rs
> +            partition_key: self.app_id.as_ref().map(|i| format!("{i}/{name}")),
If `app_id` is None will this incorrectly leave a leading forward slash in the partition key?

2024-12-18 15:41 UTC, calebschoepp commented on crates/key-value-azure/src/store.rs
> +            partition_key: self.app_id.as_ref().map(|i| format!("{i}/{name}")),
I see below that it seems like the leading slash is okay, but I'll leave the question here to double check.

2024-12-18 15:41 UTC, calebschoepp commented on crates/key-value-azure/src/store.rs
> +}
Why are these redefined here?

2025-01-03 15:35 UTC, rylev commented on crates/key-value-azure/src/store.rs
> +            partition_key: self.app_id.as_ref().map(|i| format!("{i}/{name}")),
If `app_id` is `None` then the `partition_key` will also be `None` which will cause the default of "/id" to be used.

2025-01-03 15:39 UTC, rylev commented on crates/key-value-azure/src/store.rs
> +}
Laziness. I'll try to factor out the common impl.

2025-01-08 22:49 UTC, kate-goldenring approved these changes
LGTM. Love that the enables users to get more out of one cosmos container. It would be nice to add some unit tests, maybe with something like `mockall` to assert queries and partitions are correctly set.

2025-01-08 22:49 UTC, kate-goldenring commented on crates/key-value-azure/src/store.rs
> +        query.push('\'')
What is the purpose of this trailing `\`?

2025-01-08 23:10 UTC, kate-goldenring requested changes
I am testing this locally and gets don't seem to be working as expected despite the query being formulated as expected:
```sh
SELECT * FROM c WHERE c.id='wow' AND c.partition_key='foo/default'
```

(I hard coded app id into spin to test this out for a default store)

2025-01-08 23:10 UTC, kate-goldenring commented on crates/key-value-azure/src/store.rs
>  }
Looks like `get` and `get_many` still need to be updated to be partition specific. `get_pair` still queries across all partitions:
```rust
    async fn get_pair(&self, key: &str) -> Result<Option<Pair>, Error> {
        let query = self
            .client
            .query_documents(Query::new(self.get_query(key)))
            .query_cross_partition(true)
            .max_item_count(1);
```

2025-01-08 23:58 UTC, kate-goldenring approved these changes
I realized what my issue was. The implementation assumes that the container "Partition Key" is set to /partition_key. You mention this in the description but i skipped over it accidentally. Maybe naming the partition key something else such as "store_identifier" would help.

2025-01-13 09:54 UTC, rylev commented on crates/key-value-azure/src/store.rs
> +        query.push('\'')
We're pushing single quote (`'`) on to the end of the query (to close the single quote that comes right after the `=`). The `\` escapes the `'` character since characters are always themselves enclosed in `'`'.

2025-01-13 14:35 UTC, rylev commented on crates/key-value-azure/src/store.rs
>  }
I'm not sure I understand your question. Can you reformulate it?

2025-01-13 14:35 UTC, rylev commented
I've switched from the `partition_key` partition key to `store_id`. Hopefully things are a bit clearer. I'm going to merge now to unblock some other work, and I'll add tests in a new PR.

2025-01-13 15:10 UTC, merged