feat: Implement a wildcard in http allowed_domains to allow all domains
fermyon/spin pull request #422
Opened 2022-05-02 00:53 UTC by Mossaka

2022-05-03 16:37 UTC, Mossaka commented on crates/outbound-http/Cargo.toml
> +log = "0.4"
thanks!

2022-05-03 16:37 UTC, Mossaka commented on crates/outbound-http/src/lib.rs
> +                log::info!("Allowed hosts: {:?}", domains);
changed

2022-05-10 12:25 UTC, lann requested changes

2022-05-10 12:25 UTC, lann commented on crates/outbound-http/Cargo.toml
> +wasi-experimental-http-wasmtime = { git = "https://github.com/Mossaka/wasi-experimental-http", rev = "a4e1ee14a1f2d520289185537c64c315c87c1836" }
This is still pointing at your fork.

2022-05-10 12:25 UTC, lann commented on crates/outbound-http/src/lib.rs
> +    /// `*`, then all hosts are allowed.
```suggestion
    /// the string `insecure:allow-all`, then all hosts are allowed.
```

2022-05-10 15:50 UTC, Mossaka commented on crates/outbound-http/Cargo.toml
> +wasi-experimental-http-wasmtime = { git = "https://github.com/Mossaka/wasi-experimental-http", rev = "a4e1ee14a1f2d520289185537c64c315c87c1836" }
you're right!

2022-05-11 13:10 UTC, lann approved these changes

2022-05-11 13:11 UTC, merged