docs: Add documentation for custom config
fermyon/spin pull request #464
Opened 2022-05-10 15:03 UTC by lann

2022-05-10 23:03 UTC, itowlson requested changes
Sorry, quite a few suggestions I'm afraid, possibly due to me being dim rather than the content but it didn't quite come together in my mind yet.

2022-05-10 23:03 UTC, itowlson commented on docs/content/configuration.md
> +$ spin up
Perhaps a comment here to say "this will set slot `api_key` to ... and hence set component foo's `api_key` to ...".

2022-05-10 23:03 UTC, itowlson commented on docs/content/configuration.md
> +to environment variables by upper-casing and prepending with `SPIN_APP_`:
Does this induce a restriction on permitted keys?

2022-05-10 23:05 UTC, itowlson commented
I should add... I am not sure my suggestions are good ones (especially the one about doing samples in Visual Basic 3)... please read them as possible directions to explore rather than "these are the good words"!

2022-05-11 13:28 UTC, lann commented
> Sorry, quite a few suggestions I'm afraid, possibly due to me being dim rather than the content but it didn't quite come together in my mind yet.

No problem. Honestly I intentionally didn't put a _lot_ of effort into this as I'm hoping to revamp the manifest format in the near future which would require a rewrite of these docs anyway.

2022-05-11 13:59 UTC, lann commented on docs/content/configuration.md
> +config "providers. Currently there is only one provider: the environment
Do you not use the "stanford quote in NZ?

2022-05-11 14:36 UTC, lann commented on docs/content/configuration.md
> +[Custom config slot](#custom-config-slots) values may be set at runtime by
It's all hand-wavey until we have environment/profile/thingy config to actually configure providers.

2022-05-12 08:23 UTC, radu-matei approved these changes
With some of Ivan's comments addressed, this LGTM.
(particularly if we are going to rewrite the configuration document with the upcoming changes to the manifest)

Thanks!

2022-05-12 13:04 UTC, lann commented on docs/content/configuration.md
> +config "providers. Currently there is only one provider: the environment
```suggestion
config "providers". Currently there is only one provider: the environment
```

2022-05-12 13:05 UTC, lann commented on docs/content/configuration.md
> +$ export SPIN_APP_API_KEY = "1234"
```suggestion
$ export SPIN_APP_API_KEY = "1234"  # Sets the `api_key` value.
```

2022-05-12 13:08 UTC, lann commented on docs/content/configuration.md
> +
```suggestion

Configuration keys may only contain lowercase letters and underscores between letters.

```

2022-05-12 13:16 UTC, merged