do not add revision twice
fermyon/spin pull request #553
Opened 2022-06-09 15:47 UTC by bacongobbler

When the app is created, Hippo imports all available revisions from the
bindle-server. Therefore, the call to create_and_push_bindle() is all
that is necessary to upload the revision.

https://github.com/deislabs/hippo/blob/v0.14.1/src/Application/Apps/EventHandlers/InitialRevisionImport.cs

Signed-off-by: Matthew Fisher <matt.fisher@fermyon.com>

2022-06-09 15:58 UTC, fibonacci1729 approved these changes

2022-06-13 13:22 UTC, lann commented
@michelleN Merge?

2022-06-16 16:55 UTC, michelleN approved these changes
Needs a rebase but looks good. Thanks

2022-06-16 17:00 UTC, michelleN reviewed
@bacongobbler I just did a rebase locally and tested and this didn't seem to work for me. Would you mind manually testing?

2022-06-16 17:04 UTC, michelleN requested changes
Blocking on manual test fail just to be safe.

2022-06-16 17:11 UTC, michelleN commented
So when I manually test the redeploy workflow on main by updating the route in the spin.toml file, it works. When I do the same on this branch it does not work. I'm wondering if the add channel api on Hippo is working as expected? cc/ @bacongobbler

2022-06-16 17:31 UTC, bacongobbler commented
Tested manually with a few fixes from #581 and #584. Everything works as expected.

```
bacongobbler@broodlord ~/code/spin/examples/http-rust ><> export HIPPO_URL=http://hippo.local.fermyon.link
bacongobbler@broodlord ~/code/spin/examples/http-rust ><> export BINDLE_URL=http://bindle.local.fermyon.link/v1
bacongobbler@broodlord ~/code/spin/examples/http-rust ><> export HIPPO_USERNAME=bacongobbler
bacongobbler@broodlord ~/code/spin/examples/http-rust ><> export HIPPO_PASSWORD='****************'
bacongobbler@broodlord ~/code/spin/examples/http-rust ><> ../../target/debug/spin deploy
Deployed spin-hello-world version 1.0.0+qfae3969
Available Routes:
  hello: http://spin-deploy.spin-hello-world.local.fermyon.link/hello
    A simple component that returns hello.
```

Nomad job is deployed:

![image](https://user-images.githubusercontent.com/1360539/174131375-7c89e806-176d-4e9e-bdea-560f8942d2f2.png)

URL works too:

```
><> curl http://spin-deploy.spin-hello-world.local.fermyon.link/hello
Hello, Fermyon!
```

2022-06-16 17:32 UTC, bacongobbler commented
```
><> git status
On branch fix-deploy-errors
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ../../src/commands/deploy.rs

no changes added to commit (use "git add" and/or "git commit -a")
><> git diff
diff --git a/src/commands/deploy.rs b/src/commands/deploy.rs
index 126d9bc..abef72d 100644
--- a/src/commands/deploy.rs
+++ b/src/commands/deploy.rs
@@ -113,7 +113,7 @@ pub struct DeployCommand {
     pub buildinfo: Option<BuildMetadata>,
 
     /// Deploy existing bindle if it already exists on bindle server
-    #[clap(short = 'd', long = "deploy-existing-bindle")]
+    #[clap(short = 'e', long = "deploy-existing-bindle")]
     pub redeploy: bool,
 }
 
@@ -181,7 +181,6 @@ impl DeployCommand {
         .await
         .context("Problem creating a channel in Hippo")?;
 
-        Client::add_revision(&hippo_client, name.clone(), bindle_id.version_string()).await?;
         println!(
             "Deployed {} version {}",
             name.clone(),
```

2022-06-16 17:44 UTC, merged