opt: remove needless clone
fermyon/spin pull request #648
Opened 2022-07-16 07:54 UTC by csmoe

Signed-off-by: csmoe <csmoe@msn.com>

2022-07-17 21:02 UTC, itowlson requested changes
I'm not very au fait with more sophisticated Rust idioms, but I found the use of Borrow to make a HashSet behave like a HashMap a bit disorienting (although it's ingenious and I learned something from it, so thanks!).  If this is a well-known technique then I'm okay with it; otherwise, my preference would be to go back to the HashMap-based implementation and see if there are other ways we can avoid the clone of `source` (or optimise it e.g. using an Arc).

The other clarity improvements around parameter renaming are very welcome though!

2022-08-24 14:57 UTC, dicej reviewed
I tend to agree with @itowlson on this: it's a really cool technique (which I'll definitely consider using next time I'm looking to optimize a scenario like this), but I'm not sure it's worthwhile in this case given that this code is only run once at startup for a given app.  Also, any performance gain here is likely to be tiny compared to the work done in `Linker::instantiate_pre`.

For cold path code like this, I'd say simpler is better, even if it involves a few extra allocations.

2022-08-24 14:57 UTC, dicej commented on crates/engine/src/lib.rs
> +        let mut components = HashSet::with_capacity(self.config.components.len() / 2);
Why the `/ 2` here?

2022-08-30 22:52 UTC, csmoe commented
This patch is trivial on performance, close.(Thanks for your reviewing)

2022-08-30 22:52 UTC, closed without merging