feat: add accept-defaults to new templates
fermyon/spin pull request #695
Opened 2022-08-17 16:12 UTC by karthik2804

Add optional argument `--accept-defaults` to `spin new` to accept defaults where available from the template. The values file and value mentioned in the CLI still take precedence as per the discussion in #591.

2022-08-18 02:58 UTC, radu-matei commented on src/commands/new.rs
> +                let parameters = template.as_ref().unwrap().parameters();
I know we are checking for `.is_some`, but I would still like to avoid calling `.unwrap()` here if possible.

2022-08-18 04:06 UTC, itowlson requested changes
Thanks for taking this on.  I'd strongly encourage you to dive a little deeper into the templates crate - although it requires more code reading, I believe you'll end up at an existing function where the code has both the parameter object and designated value to hand, and is performing the existing "value > prompt" logic.  Extending that to "value > accepted default > prompt" should (I hope) be a couple of lines.

Happy to chat or pair I'm not explaining myself well...

2022-08-18 04:17 UTC, itowlson commented on src/commands/new.rs
> +    /// by accepting the defaults if avaiblable on the template
typo 
```suggestion
    /// by accepting the defaults if available on the template
```

2022-08-18 20:07 UTC, itowlson requested changes
This looks good - thanks!  Couple of minor recommendations, but otherwise good to go!

2022-08-18 20:07 UTC, itowlson commented on crates/templates/src/manager.rs
> +        let values = [("http-path".to_owned(), "/path/...".to_owned())]
Suggestion: _don't_ send in a value for `http-path`, and assert that the `spin.toml` correctly gets the default value.

2022-08-18 20:07 UTC, itowlson commented on crates/templates/src/run.rs
> +                if let (Some(s), true) = (parameter.default_value(), self.options.accept_defaults) {
I think a `match` here might be Rustier:

```
None => match (self.options.acccept_defaults, parameter.default_value()) {
    (true, Some(v)) => Some(v.to_string()),
    _ => crate::interaction::prompt_parameter(parameter),
}
```

2022-08-18 20:07 UTC, itowlson commented on crates/templates/src/run.rs
> +                if let (Some(s), true) = (parameter.default_value(), self.options.accept_defaults) {
Again suggest using a `match`

2022-08-18 23:30 UTC, itowlson approved these changes
LGTM!

2022-08-19 03:11 UTC, radu-matei approved these changes

2022-08-19 03:11 UTC, merged